server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /card-ms

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: iba-admin-panel-merchant-management
  banner:
    location: classpath:static/banner.txt
  cloud:
    kubernetes:
      enabled: true

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
  endpoints:
    web:
      exposure:
        include: info, health
    enabled-by-default: false
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: false
    info:
      enabled: true

ribbon:
  eager-load:
    enabled: true

restTemplate:
  connectTimeout: 3000 # in milliseconds
  readTimeout: 3000 # in milliseconds

caching:
  enabled: true
  maxItem: 1000
  expireTime: 12 # in hours

endpoints:
  flex-card-reader: ${FLEX_CARD_READER_ENDPOINT:http://localhost:8084/flex-card-reader}
  ufx-info-ms: ${UFX_INFO_MS_ENDPOINT:http://localhost:8082/ufx-info-ms}

validation:
  maxCifListSize: 10

logging:
  level:
    org.springframework.web: DEBUG
    az.iba: DEBUG
